### ISSUE TITLE
Ghost notification

### ISSUE THREAD

**Issue by murtezayesil** [ZeonXX/Campfire#3]
After viewing every notification there is still bubble with 1 in it meaning there is still a not viewed notification.
![screenshot_20190304-170734_campfire](https://user-images.githubusercontent.com/24689015/53731365-bee8d780-3ea4-11e9-898c-94e4a215723c.png)

It can be fixed temporarily by tapping double tick on top the screen but bug reappears when a new notification arrives.
![screenshot_20190304-173221_campfire](https://user-images.githubusercontent.com/24689015/53731380-c9a36c80-3ea4-11e9-8592-ee3af349e6a7.png)

I also noticed that bubble shows the number of notifications + 1
Here it shows that I have 3 notifications while it was actually 2:
![screenshot_20190304-173926_campfire](https://user-images.githubusercontent.com/24689015/53731477-125b2580-3ea5-11e9-9898-33127c4b0591.png)
and 1 remained after viewing all the notifications:
![screenshot_20190304-173946_campfire](https://user-images.githubusercontent.com/24689015/53731529-459db480-3ea5-11e9-9de9-81b629b3a4e6.png)

**Comment by ZeonXX** [comment]
fixed
